### PR TITLE
Buildcache clash fix

### PR DESCRIPTION
**Pull request by marcmengel**
This change catches the UndefinedNamespace error thrown in environment concretization when there are packages in the buildcache that reference namespaces our spack instance doesn't have, and prunes the related items from the specs under consideration.

### CODE REVIEW

**Comment by greenc-FNAL** [comment]
Are we sure this is still a problem? I think I stopped getting this error after a recent merge from upstream.

**Comment by marcmengel** [comment]
I'm still having it on 0.19.0-dev.fermi....
hence the patch.

**Comment by greenc-FNAL** [comment]
Fair enough. I do worry though, that this is an XY problem. There's no reason a BuildCache entry from an unknown namespace shouldn't be perfectly usable: recipe and other information is there, _etc._ I can understand reticence if the entry is unsigned but otherwise it should be fine. Dropping the entries entirely just feels like it might cause hard-to-diagnose problems down the line.

**Comment by marcmengel** [comment]
Well, I'm also working around this the other way: I'm moving all the ruby/redmine stuff into a separate buildcache, since most folks aren't using it, and it just slows down and sometimes confuses  the concretization.   So maybe we should just drop this.

**Pull request closed without merging**
