### PR TITLE
Handle system-installed GL

### PR DESCRIPTION
**Pull request by greenc-FNAL**

### CODE REVIEW

**Comment by greenc-FNAL** [comment]
@spackbot style

**Comment by greenc-FNAL** [comment]
@spackbot hello!

**Comment by greenc-FNAL** [comment]
@spackbot style

**Comment by greenc-FNAL** [comment]
@spackbot commands

**Comment by greenc-FNAL** [comment]
@spackbot fix style

**Review by marcmengel — APPROVED** [review]

**Pull request merged**
