### PR TITLE
Update geant4 clhep and vecgeom to use cxxstd variant

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by greenc-FNAL** [comment]
What are the chances of this one going upstream? Forgive the scratched record, but I'm trying to keep the divergence down as much as possible.

**Comment by gartung** [comment]
Submitted a PR with the updates to add cxxstd but it does not have the g4 data downloads because they are pulling from scidet and are specific to fnal.

**Comment by gartung** [comment]
https://github.com/spack/spack/pull/10518

**Comment by greenc-FNAL** [comment]
Re the data, check with Lynn: I thought she was saying that the data needed to be separable because the don't necessarily change with version.

**Comment by gartung** [comment]
The fnal-art version does download the data as standalone packages

https://cdcvs.fnal.gov/redmine/projects/spack-planning/repository/spack_art/revisions/master/entry/packages/geant4/package.py

**Comment by greenc-FNAL** [comment]
Ah, OK: misunderstood, sorry.

**Comment by greenc-FNAL** [comment]
We should discuss what---if any---coupling we have between the geant4 package and the data packages in the recipe we actually use, and what we should try to merge upstream.

**Pull request merged**
