### PR TITLE
PackageBase should not set `(build|install)_time_test_callbacks`

### PR DESCRIPTION
**Pull request by greenc-FNAL**

### CODE REVIEW

**Comment by marcmengel** [comment]
Hm... It looks to me like there could be a problem with the audit.py code, 
`test_callbacks = pkg_cls.build_time_test_callbacks`
maybe we could add a check in there that the field is defined before they use it?

**Comment by greenc-FNAL** [comment]
I'll take a look, thanks.

**Comment by greenc-FNAL** [comment]
@marcmengel Reworked audit function to do the correct thing in a multi-builder world. Presence of legacy attributes in general will be audited by a separate function in forthcoming upstream PR.

**Review by marcmengel — APPROVED** [review]
That looks better on the front mentioned,  and more complete generally.

**Comment by greenc-FNAL** [comment]
See https://github.com/spack/spack/pull/33943 for legacy-attributes audit.

**Pull request merged**
