### PR TITLE
Updates from building CMSSW

### PR DESCRIPTION
**Pull request by gartung**

### CODE REVIEW

**Comment by greenc-FNAL** [comment]
???

**Comment by gartung** [comment]
I had some updates but I wasn't sure if you had merged the same things on your branch.

**Comment by gartung** [comment]
I force pushed and that closed the PR.

**Comment by greenc-FNAL** [comment]
The `FNALssi/spack:fnal-develop` branch is up to date with `spack/spack:develop` as of yesterday, and additionally includes PR spack/spack#8612. Not quite sure what you mean by "force-pushed:" what, and to where?

**Pull request closed without merging**
