### PR TITLE
Mwm recipes

### PR DESCRIPTION
**Pull request by marcmengel**
Assorted recipes for using spack to setup the POMS service from Fermilab, including uwsgi, cherrypy, etc.

### CODE REVIEW

**Comment by greenc-FNAL** [comment]
Is there any reason not to submit all these new recipes as (separate) upstream PRs? I'm fine with putting them in our fork first but I'd hate to be running just from our fork and then have some enterprising individual submit different versions of some of these upstream and have it turn into a merging nightmare.

For the same reason (you're going to hate me for this) I'd prefer these be individual PRs with the title, "New package: XXX" to make the merging more straightforward when they *are* accepted upstream.

**Review by greenc-FNAL — CHANGES_REQUESTED** [review]
Several of these recipes still have FIXME messages and boilerplate that should be removed. Also see [non-review comment](https://github.com/FNALssi/spack/pull/24#issuecomment-545006302) re splitting into individual PRs.

**Comment by marcmengel** [comment]
Sigh.. You're probably right.  Yes the only reason not to submit them
separately upstream is tedium :-).

**Comment by greenc-FNAL** [comment]
@marcmengel Is this PR still meaningful?

**Comment by marcmengel** [comment]
Nah, just close it out.  I'll maybe contribute some of them upstream when I get a round to-it.

**Pull request closed without merging**
