### PR TITLE
Update to current upstream/develop

### PR DESCRIPTION
**Pull request by greenc-FNAL**
Update to current upstream/develop

@marcmengel Please remind me what I should be doing to verify UPS module
config/behavior and packages.yaml require issues.

### CODE REVIEW

**Comment by marcmengel** [comment]
So I just ran a bootstrap using the branch, and got config errors which prevented the bootstrap from completing properly when we copied in our site-specific configs.

**Comment by greenc-FNAL** [comment]
I'll look into it after lunch.

**Comment by greenc-FNAL** [comment]
```
[greenc@scisoftbuild01] bin (master) (ups) $ ./bootstrap --with_padding ~/scratch/art-ci-2023-04-24a master chgtest
after while: args /home/greenc/scratch/art-ci-2023-04-24 master chgtest
Putting detail log in /tmp/bootstrap54028.log
Cloning FNALssi spack-infrastructure repository          
Setting up with make_spack                               
Finding compilers                                        
[greenc@scisoftbuild01] bin (master) (ups) $ 
```

Note: `FNALssi/chgtest` is a copy of `greenc-FNAL/update/upstream-develop-2023-04-24`.

Not sure what I should expect to be seeing, here?

**Comment by marcmengel** [comment]
Well, what I was seeing was a failure of the bootstrap, with error messages about the config files in the detail log. 
So this is an improvement.   There should also be a UPS table file and version directory/file under the directory
for patchelf.

**Comment by greenc-FNAL** [comment]
```
[greenc@scisoftbuild01] art-ci-2023-04-25 (ups) $ ls -l
total 8
drwxr-xr-x 3 greenc g163  40 Apr 25 08:49 __spack_path_placeholder__
drwxr-xr-x 2 greenc g163  19 Apr 25 08:50 bin
drwxr-xr-x 3 greenc g163  90 Apr 25 08:50 patchelf
-rw-r--r-- 1 greenc g163 202 Apr 25 08:58 setup-env.csh
-rw-r--r-- 1 greenc g163 196 Apr 25 08:58 setup-env.sh
drwxr-xr-x 3 greenc g163  36 Apr 25 08:58 spack
drwxr-xr-x 3 greenc g163  20 Apr 25 08:48 spack-infrastructure
drwxr-xr-x 3 greenc g163 102 Apr 25 08:52 spack_infrastructure
drwxr-xr-x 4 greenc g163  36 Apr 25 08:51 tmp
[greenc@scisoftbuild01] art-ci-2023-04-25 (ups) $ ls -l patchelf/
total 4
drwxr-xr-x 2 greenc g163 47 Apr 25 08:50 0.13.1.version
-rw-r--r-- 1 greenc g163 64 Apr 25 08:50 patchelf_0.13.1_n2lxs7y3igk4ljubemdjdmzbe74s7bjj.table
```

**Comment by marcmengel** [comment]
So with this branch I don't see any of the issues I saw with #107.

**Review by marcmengel — APPROVED** [review]
With this branch I do not see any of the issues I saw with #107.

**Comment by marcmengel** [comment]
So we just need style cleanup here...

**Comment by marcmengel** [comment]
Looks like if you just black-format var/spack/repos/builtin/packages/scitokens-cpp/package.py the style check would be clean.

**Pull request merged**
